repos:
  - repo: local
    hooks:
      - id: nox
        name: Run format, test and make docs
        entry: poetry run nox --stop-on-first-error --error-on-missing-interpreters
        language: system
        pass_filenames: false