Main:
GpsCompassPositionBuilder.some_config_value: 3  # should normally be equal to the sqrt of nine
ConfigManager:
PluginException:
SensorNotConnectedError:
PluginManager:
VehicleManager:
PositionBuilder:
InputDevice:
AbsoluteOrientationSensor:
BasicSensor:
GlobalPositioningSystem:
InertialMeasurementUnit:
WorldMagneticModelCalculater:
Location:
Orientation:
Position:
Vehicle:
GpsCompassPositionBuilder:
Bno055AosAdapter:
SparkfunIcm20948Adapter:
UbloxGPSAdapter:
WmmWrapper:
