VehicleManager:
  vehicles:
  - last_updated: 2022-12-06 23:17:31.517965
    last_updated_by: VehicleManager
    id: 3
    name: example_vehicle
    turn_radius_left: 69.1
    turn_radius_right: 70.3
    wheelbase: 3.2
    gps_receiver_offset:
    _gps_receiver_offset:
  current_vehicle_id: 0
PluginManager:
  loading_priority:
    CourseGenerator:
    - AHeadingParallelCourseGenerator
    MachineStateBuilder:
    - GpsAosPositionBuilder
    - GpsCompassPositionBuilder
    Navigator:
    - PurePursuitNavigator
    Plugin:
    - AHeadingParallelCourseGenerator
    - PurePursuitNavigator
    - AOSDummySensor
    - Bno055AosAdapter
    - GPSDummySensor
    - IMUDummySensor
    - SparkfunIcm20948Adapter
    - UbloxGPSAdapter
    - WmmWrapper
    - GpsAosPositionBuilder
    - GpsCompassPositionBuilder
    AbsoluteOrientationSensor:
    - AOSDummySensor
    - Bno055AosAdapter
    GlobalPositioningSystem:
    - GPSDummySensor
    - UbloxGPSAdapter
    InertialMeasurementUnit:
    - IMUDummySensor
    - SparkfunIcm20948Adapter
    WorldMagneticModelCalculator:
    - WmmWrapper
WmmWrapper:
  wmm_bin_path: example/wmm/bin/path
