VehicleManager:
  vehicles:
  - id:
    name: example_vehicle
    turn_radius_left: 69.1
    turn_radius_right: 70.3
    wheelbase: 3.2
    gps_receiver_offset:
    - 1
    - 2
    - 3
  current_vehicle_id: 0
PluginManager:
  loading_priority:
    CourseGenerator:
    - AHeadingParallelGenerator
    Navigator:
    - PurePursuitNavigator
    PositionBuilder:
    - GpsAosPositionBuilder
    - GpsCompassPositionBuilder
    UserInterface:
    - FlaskWebUI
    AbsoluteOrientationSensor:
    - AOSDummySensor
    - Bno055AosAdapter
    GlobalPositioningSystem:
    - GPSDummySensor
    - UbloxGPSAdapter
    InertialMeasurementUnit:
    - SparkfunIcm20948Adapter
    WorldMagneticModelCalculator:
    - WmmWrapper
    Plugin:
    - AHeadingParallelGenerator
    - PurePursuitNavigator
    - GpsAosPositionBuilder
    - GpsCompassPositionBuilder
    - AOSDummySensor
    - Bno055AosAdapter
    - GPSDummySensor
    - SparkfunIcm20948Adapter
    - WmmWrapper
    - FlaskWebUI
    MessageType: []
    UserInterfaceBase:
    - FastAPIUserInterface
SparkfunIcm20948Adapter:
  magnetometer_bias:
WmmWrapper:
  wmm_bin_path: example/wmm/bin/path
