VehicleManager:
  vehicles:
  - name: example_vehicle
    gps_receiver_offset:
    - 1
    - 2
    - 3
    turn_radius_right: 70.3
    turn_radius_left: 69.1
    wheelbase: 3.2
  current_vehicle_id: 0
PluginManager:
  loading_priority:
    CourseGenerator:
    - AHeadingParallelCourseGenerator
    MachineStateBuilder:
    - GpsAosPositionBuilder
    - GpsCompassPositionBuilder
    Navigator:
    - PurePursuitNavigator
    Plugin:
    - AHeadingParallelCourseGenerator
    - PurePursuitNavigator
    - AOSDummySensor
    - Bno055AosAdapter
    - GPSDummySensor
    - IMUDummySensor
    - SparkfunIcm20948Adapter
    - UbloxGPSAdapter
    - WmmWrapper
    - GpsAosPositionBuilder
    - GpsCompassPositionBuilder
    AbsoluteOrientationSensor:
    - AOSDummySensor
    - Bno055AosAdapter
    GlobalPositioningSystem:
    - GPSDummySensor
    - UbloxGPSAdapter
    InertialMeasurementUnit:
    - IMUDummySensor
    - SparkfunIcm20948Adapter
    WorldMagneticModelCalculator:
    - WmmWrapper
