version: "3.9"  # optional since v1.27.0
services:
  open_precision:
    build:
      context: .
      target: runtime
      dockerfile: Dockerfile
      tags:
        - larsjaeger/open_precision:latest
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    image: larsjaeger/open_precision
    restart: always
    privileged: true
    ports:
      - "8000:8000"
    volumes:
      - /dev:/dev
    networks:
      - internal
    depends_on:
      - redis
      - neo4j
  redis:
    image: redis:alpine
    restart: unless-stopped
    expose:
      - 6379
    networks:
      - internal
    command: redis-server --loglevel warning
  neo4j:
    image: neo4j:latest
    restart: always
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/password
    expose:
      - 7474
      - 7473
      - 7687
    networks:
      - internal
networks:
  internal: {}