version: "3.9"  # optional since v1.27.0
services:
  open_precision:
    # build: .
    image: larsjaeger/open_precision
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - /dev:/dev
    networks:
      - internal
    depends_on:
      - redis
  redis:
    image: redis:alpine
    restart: always
    expose:
      - 6379
    networks:
      - internal
    command: redis-server --loglevel warning
networks:
  internal: {}