version: "3.9"  # optional since v1.27.0
services:
  open_precision:
    build:
      context: .
      target: runtime
      dockerfile: Dockerfile
      tags:
        - larsjaeger/open_precision:latest
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
          - linux/arm/v7
          - linux/arm/v6
    image: larsjaeger/open_precision
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - /dev:/dev
    networks:
      - internal
    depends_on:
      - redis
  redis:
    image: redis:alpine
    restart: always
    expose:
      - 6379
    networks:
      - internal
    command: redis-server --loglevel warning
  neo4j:
    image: neo4j:latest
    restart: always
    expose:
      - 7474
      - 7473
      - 7687
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
    networks:
      - internal
networks:
  internal: {}